### ISSUE TITLE
Getting an error in image count

### ISSUE THREAD

**Issue by saint2706** [hrithwikbharadwaj/redditToInstaBot#1]
![image](https://user-images.githubusercontent.com/45678566/90054851-0c07e480-dcfa-11ea-9d38-37c01bfd6095.png)

How do i fix this? Pic related

**Comment by hrithwikbharadwaj** [comment]
I guess it's because max_images variable in the code doesn't have value specified.

Try adding this line in the initial code after import statements
```
max_images=3
```
